<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CourseMaterialController extends Controller
{
    public function index($id)
    {
        // Data materi
        $materials = [
            1 => [
                'title' => 'Internet of Things for Beginner',
                'content' => 'Internet of Things (IoT) adalah sebuah konsep revolusioner di mana benda-benda fisik yang kita gunakan sehari-hari dapat saling berkomunikasi melalui internet. Ide utamanya adalah menghubungkan perangkat fisik seperti sensor, kamera, lampu, dan banyak lagi ke internet, untuk melakukan berbagai macam hal seperti mengontrol, memantau, dan mengumpulkan data secara otomatis. Teknologi IoT mengubah cara kita berinteraksi dengan dunia sekitar. Misalnya, Anda bisa mengatur suhu rumah dari jarak jauh, memantau kelembapan tanah di kebun Anda, atau bahkan mengendalikan perangkat rumah tangga hanya dengan menggunakan smartphone. Dalam kursus ini, Anda akan belajar tentang alat dasar yang digunakan untuk membuat sistem IoT seperti Raspberry Pi dan Arduino, serta berbagai jenis sensor yang digunakan untuk mengukur suhu, kelembapan, cahaya, dan gerakan. Anda juga akan diajarkan cara menghubungkan perangkat ke internet menggunakan jaringan Wi-Fi atau Ethernet, serta bagaimana data dapat dikirimkan ke server atau cloud untuk dianalisis lebih lanjut. Pelajaran ini juga akan membahas tentang berbagai protokol komunikasi yang digunakan dalam IoT, seperti MQTT yang sering digunakan dalam komunikasi antar perangkat dan HTTP untuk aplikasi berbasis web. Di akhir kursus, Anda akan memiliki pemahaman dasar yang kuat tentang bagaimana mengembangkan aplikasi IoT yang dapat digunakan dalam berbagai bidang, mulai dari rumah pintar hingga pertanian pintar.'
            ],
            2 => [
                'title' => 'JavaScript Essentials',
                'content' => 'JavaScript adalah bahasa pemrograman yang digunakan untuk membangun halaman web dinamis. Jika Anda pernah berinteraksi dengan elemen di halaman web seperti tombol yang mengubah warna, gambar yang bergeser, atau form yang memvalidasi data secara otomatis, maka JavaScript-lah yang membuat itu semua mungkin. Dalam materi ini, Anda akan memulai dengan dasar-dasar JavaScript, mulai dari variabel yang menyimpan data, hingga struktur kontrol seperti perulangan dan percabangan yang memungkinkan program Anda untuk membuat keputusan berdasarkan kondisi tertentu. Kami akan mengajarkan Anda bagaimana menggunakan fungsi untuk mengorganisir kode Anda, serta bagaimana cara mengirimkan data antar fungsi. Selain itu, Anda akan mempelajari cara JavaScript berinteraksi dengan elemen HTML melalui DOM (Document Object Model), yang memungkinkan Anda untuk memperbarui tampilan halaman secara dinamis. Misalnya, Anda dapat membuat halaman web yang berubah berdasarkan input pengguna tanpa perlu memuat ulang halaman. Anda juga akan belajar bagaimana bekerja dengan objek dan array, yang sering digunakan untuk menyimpan data yang lebih kompleks. Pelajaran ini juga mencakup event handling, di mana Anda akan belajar bagaimana cara menambahkan interaksi dengan pengguna, seperti klik tombol atau perubahan nilai input. Dengan menguasai dasar-dasar JavaScript, Anda akan siap untuk membuat aplikasi web yang lebih interaktif dan dinamis.'
            ],
            3 => [
                'title' => 'Advanced CSS Animations',
                'content' => 'CSS Animations memberi Anda kemampuan untuk menambahkan elemen visual yang menarik dan interaktif pada situs web Anda, tanpa perlu menggunakan JavaScript. Animasi ini dapat mempercantik transisi antar halaman, menambahkan efek hover pada tombol, atau membuat elemen bergerak di halaman. Dalam materi ini, Anda akan belajar cara menggunakan CSS Keyframes, yang memungkinkan Anda untuk mendefinisikan sebuah animasi dari awal hingga akhir, serta menentukan bagaimana perubahan terjadi di setiap titik waktu dalam animasi tersebut. Anda akan memahami konsep dasar dari properti animasi, seperti `animation-duration`, `animation-delay`, dan `animation-timing-function`, yang membantu Anda mengatur durasi animasi dan timing-nya. Selain itu, Anda akan mempelajari bagaimana cara menggunakan transformasi CSS, seperti rotasi, pembesaran (scaling), dan pergeseran (translation), untuk menciptakan efek-efek visual yang dinamis. Misalnya, Anda dapat membuat tombol yang membesar saat kursor diarahkan atau membuat elemen yang berputar dengan halus. Kursus ini juga membahas teknik transisi CSS, di mana Anda akan belajar bagaimana memanipulasi properti elemen dengan mulus saat terjadi perubahan status, seperti saat pengguna mengarahkan kursor ke elemen atau ketika elemen menerima fokus. Selain itu, Anda akan belajar cara mengoptimalkan performa animasi CSS untuk memastikan bahwa animasi tetap lancar dan tidak membebani kinerja halaman, terutama pada perangkat mobile yang memiliki keterbatasan sumber daya.'
            ],
            4 => [
                'title' => 'HTML Basics',
                'content' => 'HTML, singkatan dari HyperText Markup Language, adalah dasar dari setiap halaman web yang Anda lihat di internet. HTML memberikan struktur dan kerangka kerja untuk halaman web, mengatur elemen-elemen seperti teks, gambar, dan tautan dengan cara yang mudah dibaca dan dipahami oleh browser. Dalam materi ini, Anda akan mempelajari cara menggunakan elemen-elemen dasar HTML, seperti heading untuk judul, paragraf untuk teks, dan daftar untuk membuat daftar yang terstruktur. Anda juga akan belajar cara menambahkan gambar dan video ke dalam halaman web menggunakan tag `<img>` dan `<video>`, serta bagaimana cara membuat tabel untuk menampilkan data dalam format yang lebih terorganisir. Selain itu, Anda akan belajar bagaimana cara membuat form interaktif menggunakan elemen-elemen seperti input, textarea, dan button, yang memungkinkan pengguna untuk mengirimkan data ke server. Materi ini juga mengajarkan penggunaan elemen-elemen semantik, seperti `<header>`, `<footer>`, dan `<article>`, yang membantu membuat halaman web lebih mudah dipahami oleh mesin pencari dan teknologi aksesibilitas. Dengan dasar yang kuat dalam HTML, Anda akan dapat membuat halaman web yang lebih mudah diakses dan lebih terstruktur dengan baik.'
            ],
            5 => [
                'title' => 'React.js for Intermediate Developers',
                'content' => 'React.js adalah salah satu library JavaScript yang paling populer untuk membangun aplikasi web yang responsif dan dinamis. Dalam kursus ini, Anda akan belajar cara bekerja dengan komponen fungsional di React, yang memungkinkan Anda untuk membangun antarmuka pengguna dengan cara yang lebih modular dan terstruktur. Anda akan mendalami penggunaan state dan props untuk mengelola data dalam aplikasi Anda, serta mempelajari bagaimana cara menggunakan `useState` dan `useEffect`, dua hooks utama di React. `useState` memungkinkan Anda untuk menyimpan dan mengubah data dalam komponen, sedangkan `useEffect` memungkinkan Anda untuk menjalankan efek samping, seperti memuat data dari API atau mengupdate DOM. Anda juga akan mempelajari cara menggunakan React Router untuk mengelola navigasi antar halaman dalam aplikasi Anda, tanpa perlu me-refresh halaman. Kursus ini juga mengajarkan tentang pengelolaan state global menggunakan Context API atau Redux, yang sangat berguna ketika aplikasi Anda tumbuh besar dan membutuhkan cara yang lebih terstruktur untuk mengelola data. Selain itu, Anda akan mempelajari cara melakukan pengujian unit menggunakan Jest dan Enzyme untuk memastikan bahwa aplikasi Anda bekerja dengan baik dan bebas dari bug. Di akhir kursus, Anda akan membangun aplikasi React yang lebih kompleks, seperti aplikasi manajemen tugas atau aplikasi berita yang dapat memuat data dari API eksternal.'
            ],
            6 => [
                'title' => 'Python for Data Science',
                'content' => 'Python adalah bahasa pemrograman yang sangat populer dalam bidang data science karena sintaksisnya yang mudah dipahami dan kekuatan pustaka yang luas. Dalam kursus ini, Anda akan mempelajari pustaka-pustaka Python yang paling penting untuk analisis data, seperti NumPy untuk komputasi numerik, Pandas untuk manipulasi data, dan Matplotlib serta Seaborn untuk visualisasi data. Anda akan belajar cara melakukan eksplorasi data dengan menggunakan statistik dasar, seperti mean, median, dan standar deviasi, serta cara visualisasi data dengan grafik yang dapat membantu Anda memahami pola dan tren yang tersembunyi dalam data. Kursus ini juga mencakup topik pengolahan data, termasuk cara membersihkan data (data cleaning), menangani nilai yang hilang, serta merubah data agar lebih mudah dianalisis. Anda juga akan mempelajari teknik analisis yang lebih lanjut seperti regresi linear untuk memprediksi nilai kontinu dan klasifikasi untuk memprediksi kategori. Selain itu, kursus ini juga mengajarkan cara menggunakan pustaka Scikit-learn untuk membuat model machine learning, serta cara menguji akurasi model menggunakan teknik validasi silang. Di akhir kursus, Anda akan membangun dan menguji model prediksi menggunakan dataset nyata, seperti data harga saham atau data penjualan, serta mempelajari bagaimana cara membuat laporan dan presentasi yang jelas untuk menyampaikan hasil analisis data kepada stakeholder.'
            ],
            7 => [
                'title' => 'Beginner’s Guide to Cybersecurity',
                'content' => 'Keamanan siber adalah salah satu topik yang sangat penting di dunia digital saat ini. Dalam kursus ini, Anda akan belajar bagaimana melindungi sistem komputer dan data dari ancaman yang semakin canggih. Kursus ini dimulai dengan pengenalan terhadap berbagai jenis ancaman siber, seperti malware, ransomware, dan phishing. Anda akan mempelajari bagaimana cara mengenali tanda-tanda serangan dan bagaimana cara melindungi sistem dengan menggunakan perangkat lunak keamanan seperti antivirus dan firewall. Anda juga akan belajar tentang enkripsi, yaitu teknik untuk melindungi data agar hanya bisa dibaca oleh pihak yang berwenang. Materi ini juga mencakup pengelolaan kata sandi yang aman, serta bagaimana cara menggunakan autentikasi dua faktor untuk meningkatkan keamanan akun online Anda. Selain itu, Anda akan mempelajari prinsip-prinsip dasar dari keamanan jaringan, seperti penggunaan VPN untuk menjaga privasi online dan IDS/IPS untuk mendeteksi dan mencegah serangan. Kursus ini juga mengajarkan cara melindungi aplikasi web dari potensi kerentanannya, serta bagaimana cara menanggapi insiden keamanan dan merespons serangan dengan cepat dan efisien. Dengan kursus ini, Anda akan memiliki pemahaman yang baik tentang dasar-dasar keamanan siber dan langkah-langkah yang dapat diambil untuk melindungi data pribadi dan organisasi Anda.'
            ],
            8 => [
                'title' => 'Node.js and Express Essentials',
                'content' => 'Node.js adalah runtime JavaScript yang memungkinkan Anda untuk menjalankan JavaScript di sisi server. Dalam kursus ini, Anda akan mempelajari bagaimana cara membuat server web dengan Node.js dan bagaimana cara menangani berbagai permintaan HTTP. Anda akan diajarkan cara menggunakan Express, sebuah framework minimalis untuk Node.js, untuk membuat aplikasi web dan API yang cepat dan efisien. Kursus ini akan mengajarkan Anda tentang routing di Express, serta bagaimana cara menggunakan middleware untuk memproses data sebelum mencapai route handler. Anda juga akan belajar cara membuat aplikasi RESTful yang dapat berinteraksi dengan database seperti MongoDB atau MySQL, dan cara menangani permintaan CRUD (Create, Read, Update, Delete). Selain itu, Anda akan mempelajari cara menggunakan template engine seperti EJS untuk menghasilkan HTML dinamis, serta bagaimana cara mengoptimalkan kinerja aplikasi Anda menggunakan teknik caching dan kompresi data. Di akhir kursus, Anda akan dapat membangun aplikasi web yang sepenuhnya berfungsi menggunakan Node.js dan Express, serta siap untuk mengintegrasikan aplikasi Anda dengan berbagai layanan dan API eksternal.'
            ],
            9 => [
                'title' => 'Machine Learning for Beginners',
                'content' => 'Machine Learning (ML) adalah cabang dari kecerdasan buatan yang memungkinkan sistem untuk belajar dan membuat keputusan berdasarkan data, tanpa pemrograman eksplisit. ML digunakan di berbagai bidang, dari analisis data, pengenalan wajah, rekomendasi produk, hingga mobil yang dapat mengemudi sendiri. Dalam kursus ini, Anda akan belajar tentang dasar-dasar Machine Learning dan bagaimana cara mengimplementasikannya menggunakan Python, salah satu bahasa pemrograman yang paling populer untuk ML. Kursus ini dimulai dengan pengenalan terhadap berbagai jenis pembelajaran mesin, yaitu pembelajaran terawasi (supervised learning), pembelajaran tidak terawasi (unsupervised learning), dan pembelajaran penguatan (reinforcement learning). Anda akan mempelajari bagaimana menggunakan data untuk melatih model dalam supervised learning, di mana model belajar dari data berlabel untuk memprediksi hasil tertentu, seperti mengklasifikasikan email sebagai spam atau tidak spam. Anda juga akan belajar tentang algoritma regresi, seperti regresi linier, yang digunakan untuk memprediksi nilai kontinu berdasarkan variabel input. Dalam pembelajaran tidak terawasi, Anda akan mempelajari teknik seperti klasterisasi, di mana model mengelompokkan data tanpa menggunakan label, yang berguna untuk menemukan pola dalam data besar tanpa pengawasan. Anda juga akan diperkenalkan pada teknik-teknik evaluasi model, seperti confusion matrix dan cross-validation, untuk menilai kinerja model ML. Kursus ini juga mengajarkan penggunaan pustaka Python populer seperti Scikit-learn, TensorFlow, dan Keras, yang memudahkan proses pembangunan dan penerapan model ML. Di akhir kursus, Anda akan membangun dan menguji model prediksi menggunakan dataset nyata, seperti data pengenalan wajah atau analisis sentimen dari teks. Anda akan belajar cara mengoptimalkan model dengan teknik seperti fine-tuning parameter dan menggunakan algoritma yang lebih canggih seperti Random Forest dan Support Vector Machine (SVM). Dengan pemahaman dasar yang kuat tentang Machine Learning, Anda akan siap untuk menerapkan teknik-teknik ini dalam proyek dunia nyata dan memperluas pengetahuan Anda ke bidang yang lebih kompleks seperti Deep Learning dan Neural Networks.'
            ],          
        ];

        // Ambil materi berdasarkan ID
        $courseMaterial = $materials[$id] ?? null;

        if (!$courseMaterial) {
            return view('errors.404');
        }

        return view('courses.materi', [
            'material' => $materials[$id]
        ]);
    }
}
